# Generated by Django 5.2.2 on 2026-09-08 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompareSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compare_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compare_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompareResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField()),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('token_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compare_results', to='chats.aimodel')),
                ('compare_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='compare.comparesession')),
            ],
            options={
                'db_table': 'compare_result_items',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['compare_session'], name='compare_res_compare_3fbc77_idx')],
            },
        ),
    ]
