# Generated by Django 5.2.2 on 2026-09-08 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('compare', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_prompt', models.TextField()),
                ('review_output', models.TextField()),
                ('verdict', models.CharField(choices=[('verified', 'Verified Accurate'), ('conflicting', 'Conflicting Information'), ('needs_review', 'Needs Human Review'), ('inaccurate', 'Inaccurate / Hallucination')], default='verified', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_compare_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='compare.compareresultitem')),
                ('source_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='chats.chatmessage')),
                ('verifying_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='verifications_conducted', to='chats.aimodel')),
            ],
            options={
                'db_table': 'verify_reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
