# Generated by Django 5.2.2 on 2026-09-11 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anonymous_clients',
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='anonymous_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_sessions', to='chats.anonymousclient'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['anonymous_client', '-updated_at'], name='chat_sessio_anonymo_2f115d_idx'),
        ),
    ]
