import { useState, useEffect } from 'react';
import { Sparkles, CheckCircle2, AlertTriangle, XCircle, ChevronDown, ChevronRight, Edit3, Search, FileText, ArrowRight, Upload, ShieldCheck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';


import { verifyService } from '@/services/verifyService';
import type { VerificationData } from '@/services/verifyService';

const getIcon = (iconName: string) => {
  const icons: Record<string, any> = { CheckCircle2, AlertTriangle, XCircle };
  return icons[iconName] || CheckCircle2;
};

export function VerifyView() {
  const [webSearchEnabled, setWebSearchEnabled] = useState(false);
  const [mockVerificationData, setMockVerificationData] = useState<VerificationData | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      const data = await verifyService.getVerificationResults();
      setMockVerificationData(data);
    };
    fetchData();
  }, []);

  if (!mockVerificationData) {
    return <div className="flex items-center justify-center h-full pt-32 text-muted-foreground animate-pulse">Running verification...</div>;
  }

  return (
    <div className="max-w-[1600px] w-full mx-auto flex flex-col xl:flex-row gap-6 pb-20 md:pb-12 h-full overflow-y-auto scrollbar-hide pr-2">
      
      {/* Main Content Area */}
      <div className="flex-1 flex flex-col gap-6">
        
        {/* Header */}
        <div className="flex flex-col shrink-0 mt-2">
          <h1 className="text-2xl md:text-3xl font-bold mb-1 md:mb-2 tracking-tight">Verify</h1>
          <p className="text-muted-foreground text-[14px] md:text-[15px]">Get independent verification and fact-checking for any answer.</p>
        </div>

        {/* Original Answer Box */}
        <div className="bg-card text-card-foreground shadow-sm border border-border/50 rounded-2xl shrink-0 flex flex-col p-4 md:p-8">
            <div className="flex flex-col md:flex-row md:items-center justify-between mb-4 md:mb-6 gap-3">
               <div className="flex flex-col gap-1">
                 <h3 className="text-[15px] font-bold text-foreground">Original Answer</h3>
                 <span className="text-[12px] text-muted-foreground md:hidden">Generated by AI</span>
               </div>
               <div className="flex items-center gap-3">
                 <Badge variant="outline" className="hidden md:flex px-3 py-1.5 text-[13px] font-bold gap-2 shadow-xs bg-indigo-50/50 dark:bg-indigo-900/10 border-indigo-100 dark:border-indigo-800/30 text-indigo-700 dark:text-indigo-400 rounded-lg">
                    <Sparkles className="w-3.5 h-3.5" /> {mockVerificationData.originalAnswer.model}
                 </Badge>
                 <Button variant="outline" size="sm" className="hidden md:flex h-9 px-4 gap-2 rounded-lg font-semibold text-[13px] border-border/60 hover:bg-muted/50 shadow-xs text-foreground">
                    <Edit3 className="w-3.5 h-3.5" /> Edit Answer
                 </Button>
               </div>
            </div>
            
            <p className="text-[15px] leading-relaxed text-foreground/90 font-medium mb-8">
              {mockVerificationData.originalAnswer.text}
            </p>

            <div className="flex items-center gap-5 pt-5 border-t border-border/50">
               <span className="text-[13px] font-bold text-foreground">Sources ({mockVerificationData.originalAnswer.sourcesCount})</span>
               <div className="flex items-center gap-2">
                 <div className="w-7 h-7 rounded-lg border border-border/50 bg-background flex items-center justify-center shadow-xs"><FileText className="w-3.5 h-3.5 text-muted-foreground" /></div>
                 <div className="w-7 h-7 rounded-lg bg-zinc-100 dark:bg-zinc-800 flex items-center justify-center shadow-xs"><span className="text-[11px] font-bold">W</span></div>
                 <div className="w-7 h-7 rounded-lg bg-blue-50 dark:bg-blue-900/30 flex items-center justify-center shadow-xs"><ShieldCheck className="w-4 h-4 text-blue-600 dark:text-blue-400" /></div>
                 <div className="w-7 h-7 rounded-lg bg-blue-50 dark:bg-blue-950 text-blue-700 dark:text-blue-400 flex items-center justify-center shadow-xs"><span className="text-[11px] font-bold">in</span></div>
                 <div className="w-7 h-7 rounded-lg bg-muted flex items-center justify-center shadow-xs"><span className="text-[11px] font-bold text-muted-foreground">+2</span></div>
               </div>
            </div>
        </div>

        {/* Independent Verification Section */}
        <div className="hidden md:flex items-center gap-5 mt-2 shrink-0">
          <h3 className="font-bold text-[15px]">Independent Verification</h3>
          <Button variant="outline" className="h-9 px-4 gap-2 rounded-lg font-bold text-[13px] border-border/60 shadow-xs bg-background">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-purple-600"><path d="M12 2v20"></path><path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
            GPT-4o
            <ChevronDown className="w-3.5 h-3.5 text-muted-foreground ml-1" />
          </Button>
          <div className="flex items-center gap-2 ml-4">
            <span className="text-[13px] font-bold text-muted-foreground">Web Search</span>
            <Switch checked={webSearchEnabled} onCheckedChange={setWebSearchEnabled} className="data-[state=checked]:bg-indigo-500 scale-90" />
          </div>
        </div>

        {/* Mobile: Independent Review Summary */}
        <div className="md:hidden flex flex-col gap-4 mt-2">
           <h3 className="text-[15px] font-bold text-foreground mb-2">Independent Review</h3>
           
           <div className="flex flex-col gap-4 text-[13px] leading-relaxed">
              <div className="flex items-start gap-2.5">
                 <CheckCircle2 className="w-4 h-4 mt-0.5 text-emerald-500 shrink-0" />
                 <div><span className="font-bold text-emerald-600">Correct</span> The Eiffel Tower is 330 meters tall and was completed in 1889.</div>
              </div>
              <div className="flex items-start gap-2.5">
                 <AlertTriangle className="w-4 h-4 mt-0.5 text-amber-500 shrink-0" />
                 <div><span className="font-bold text-amber-600">Potential issue</span> Completion year is 1889 (not 1888).</div>
              </div>
              <div className="flex items-start gap-2.5">
                 <XCircle className="w-4 h-4 mt-0.5 text-red-500 shrink-0" />
                 <div><span className="font-bold text-red-600">Missing</span> Could mention it's located in Paris, France.</div>
              </div>
           </div>

           <div className="bg-card text-card-foreground shadow-sm border border-border/50 rounded-xl p-4 mt-2 flex items-center justify-between">
              <div className="flex flex-col">
                <span className="font-bold text-[14px]">Verification Result</span>
                <span className="text-red-500 font-medium text-[13px]">1 issue found</span>
              </div>
              <ChevronRight className="w-5 h-5 text-muted-foreground" />
           </div>
        </div>

        {/* Desktop: Verification Results Table */}
        <div className="hidden md:flex bg-card text-card-foreground shadow-sm border border-border/50 rounded-2xl flex-col overflow-hidden shrink-0">
          
          <div className="p-6 border-b border-border/50 bg-background flex flex-col md:flex-row md:items-center justify-between gap-4">
            <div className="flex items-center gap-3.5">
              <div className="w-10 h-10 bg-indigo-50 dark:bg-indigo-900/20 rounded-xl flex items-center justify-center shadow-xs border border-indigo-100 dark:border-indigo-800/30">
                <Sparkles className="w-5 h-5 text-indigo-600 dark:text-indigo-400" />
              </div>
              <div>
                <h3 className="font-bold text-[14px]">Verification Results</h3>
                <p className="text-[12px] text-muted-foreground font-medium">Our independent analysis of the claims in this answer</p>
              </div>
            </div>
            
            <div className="flex flex-nowrap items-center gap-2 overflow-x-auto scrollbar-hide shrink-0 max-w-full pb-1 md:pb-0">
               <div className="flex items-center gap-1.5 px-2.5 py-1 bg-indigo-50/50 dark:bg-indigo-900/20 border border-indigo-100/50 dark:border-indigo-800/30 rounded-md text-[12px] font-bold text-indigo-700 dark:text-indigo-400 shadow-[0_1px_2px_rgba(0,0,0,0.02)] transition-colors hover:bg-indigo-50 dark:hover:bg-indigo-900/40 cursor-default whitespace-nowrap shrink-0">
                 <span className="text-indigo-600 dark:text-indigo-400 text-[13px]">{mockVerificationData.metrics.totalClaims}</span> Total Claims
               </div>
               <div className="flex items-center gap-1.5 px-2.5 py-1 bg-emerald-50/50 dark:bg-emerald-900/20 border border-emerald-100/50 dark:border-emerald-800/30 rounded-md text-[12px] font-bold text-emerald-700 dark:text-emerald-400 shadow-[0_1px_2px_rgba(0,0,0,0.02)] transition-colors hover:bg-emerald-50 dark:hover:bg-emerald-900/40 cursor-default whitespace-nowrap shrink-0">
                 <span className="text-[13px]">{mockVerificationData.metrics.correct}</span> Correct
               </div>
               <div className="flex items-center gap-1.5 px-2.5 py-1 bg-amber-50/50 dark:bg-amber-900/20 border border-amber-100/50 dark:border-amber-800/30 rounded-md text-[12px] font-bold text-amber-700 dark:text-amber-400 shadow-[0_1px_2px_rgba(0,0,0,0.02)] transition-colors hover:bg-amber-50 dark:hover:bg-amber-900/40 cursor-default whitespace-nowrap shrink-0">
                 <span className="text-[13px]">{mockVerificationData.metrics.partiallyCorrect}</span> Partially Correct
               </div>
               <div className="flex items-center gap-1.5 px-2.5 py-1 bg-red-50/50 dark:bg-red-900/20 border border-red-100/50 dark:border-red-800/30 rounded-md text-[12px] font-bold text-red-700 dark:text-red-400 shadow-[0_1px_2px_rgba(0,0,0,0.02)] transition-colors hover:bg-red-50 dark:hover:bg-red-900/40 cursor-default whitespace-nowrap shrink-0">
                 <span className="text-[13px]">{mockVerificationData.metrics.incorrect}</span> Incorrect
               </div>
            </div>
          </div>

          <div className="p-0 overflow-x-auto">
             <table className="w-full text-[13px] text-left border-collapse">
               <thead className="text-muted-foreground font-bold border-b border-border/50">
                 <tr>
                   <th className="px-6 py-4 font-bold">Claim</th>
                   <th className="px-6 py-4 font-bold">Assessment</th>
                   <th className="px-6 py-4 font-bold">Details</th>
                   <th className="px-6 py-4"></th>
                 </tr>
               </thead>
               <tbody className="divide-y divide-border/50">
                 {mockVerificationData.claims.map((claim, i) => {
                   const Icon = getIcon(claim.iconName);
                   return (
                   <tr key={i} className="hover:bg-muted/30 transition-colors group">
                     <td className="px-6 py-4 flex items-start gap-3 w-full max-w-lg">
                       <Icon className={`w-4 h-4 mt-0.5 shrink-0 ${claim.color}`} />
                       <span className="font-bold text-foreground leading-relaxed">{claim.text}</span>
                     </td>
                     <td className="px-6 py-4 whitespace-nowrap align-top pt-4">
                       <span className={`font-bold ${claim.color}`}>{claim.status}</span>
                     </td>
                     <td className="px-6 py-4 text-muted-foreground font-medium align-top pt-4">{claim.details}</td>
                     <td className="px-6 py-4 text-right align-top pt-4">
                       <ChevronDown className="w-4 h-4 text-muted-foreground/50 group-hover:text-foreground transition-colors inline-block cursor-pointer" />
                     </td>
                   </tr>
                 )})}
               </tbody>
             </table>
          </div>

          <div className="p-5 border-t border-border/50 flex items-center justify-between gap-3 bg-background rounded-b-2xl">
             <Button variant="outline" className="h-9 px-4 gap-2 bg-background rounded-lg shadow-xs font-bold text-[13px] text-foreground hover:bg-muted/50 border-border/60">
               Show Evidence & Sources for All Claims <ChevronDown className="w-4 h-4" />
             </Button>
             <Button variant="outline" className="h-9 px-4 gap-2 bg-background rounded-lg shadow-xs font-bold text-[13px] text-foreground hover:bg-muted/50 border-border/60">
               <Upload className="w-4 h-4" /> Export Report
             </Button>
          </div>
        </div>
      </div>

      {/* Right Sidebar (Desktop only) */}
      <div className="hidden xl:flex flex-col w-85 gap-6 shrink-0">
         
         {/* Verification Summary */}
         <div className="bg-card text-card-foreground shadow-sm border border-border/50 rounded-2xl p-6">
             <h3 className="font-bold text-[15px] mb-6 flex items-center gap-2">
                <ShieldCheck className="w-4 h-4 text-indigo-600" /> Verification Summary
             </h3>
             <div className="flex items-center gap-8 mb-2">
                <div className="relative w-28 h-28 flex items-center justify-center shrink-0 ml-2">
                   <svg viewBox="0 0 36 36" className="w-full h-full -rotate-90 drop-shadow-sm">
                     <path className="text-muted stroke-current" strokeWidth="2.5" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                     <path className="text-emerald-500 stroke-current" strokeWidth="2.5" strokeDasharray="80, 100" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                     <path className="text-amber-500 stroke-current" strokeWidth="2.5" strokeDasharray="10, 100" strokeDashoffset="-80" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                     <path className="text-red-500 stroke-current" strokeWidth="2.5" strokeDasharray="10, 100" strokeDashoffset="-90" fill="none" d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831" />
                   </svg>
                   <div className="absolute inset-0 flex flex-col items-center justify-center">
                      <span className="text-2xl font-bold text-foreground">{mockVerificationData.metrics.accuracy}%</span>
                      <span className="text-[9px] text-muted-foreground uppercase text-center font-bold tracking-wider mt-0.5">Overall<br/>Accuracy</span>
                   </div>
                </div>
                <div className="flex flex-col gap-4 text-[13px] font-bold text-muted-foreground">
                   <div className="flex items-center gap-2"><div className="w-2.5 h-2.5 rounded-full bg-emerald-500 shadow-sm"></div> <span className="text-emerald-700 dark:text-emerald-400">{mockVerificationData.metrics.correct} Correct</span></div>
                   <div className="flex items-center gap-2"><div className="w-2.5 h-2.5 rounded-full bg-amber-500 shadow-sm"></div> <span className="text-amber-600 dark:text-amber-400">{mockVerificationData.metrics.partiallyCorrect} Partially Correct</span></div>
                   <div className="flex items-center gap-2"><div className="w-2.5 h-2.5 rounded-full bg-red-500 shadow-sm"></div> <span className="text-red-600 dark:text-red-400">{mockVerificationData.metrics.incorrect} Incorrect</span></div>
                </div>
             </div>
         </div>

         {/* Key Issues Found */}
         <div className="bg-card text-card-foreground shadow-sm border border-border/50 rounded-2xl p-6">
             <div className="flex flex-col mb-6">
                <div className="flex items-center justify-between mb-2">
                  <h4 className="font-bold text-[15px]">Key Issues Found</h4>
                  <Badge variant="destructive" className="bg-red-50 text-red-700 hover:bg-red-50 border-red-200 dark:border-red-900 font-bold rounded-full px-2 py-0.5 text-[10px] shadow-xs">
                    1 High Priority
                  </Badge>
                </div>
             </div>

             <div className="flex flex-col gap-5">
               {mockVerificationData.keyIssues.map((issue, i) => {
                 const Icon = getIcon(issue.iconName);
                 return (
                 <div key={i} className="flex items-start gap-4 p-4 rounded-xl border border-border/50 bg-background hover:shadow-sm transition-all">
                    <div className={`p-2 rounded-lg ${issue.bgClass}`}>
                      <Icon className={`w-5 h-5 ${issue.colorClass}`} />
                    </div>
                    <div>
                     <h5 className="text-[13px] font-bold text-foreground leading-snug mb-1">{issue.title}</h5>
                     <p className="text-[12px] text-muted-foreground font-medium leading-relaxed">{issue.description}</p>
                   </div>
                 </div>
               )})}
             </div>
         </div>

         {/* Recommendations */}
         <div className="bg-card text-card-foreground shadow-sm border border-border/50 rounded-2xl p-6">
             <h4 className="font-bold text-[15px] mb-5">Recommendations</h4>
             <ul className="space-y-4">
               {mockVerificationData.recommendations.map((rec, idx) => (
                 <li key={idx} className="flex items-start gap-2.5 text-[13px] text-muted-foreground font-medium"><CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 bg-emerald-50 rounded-full" /> <span className="leading-relaxed">{rec}</span></li>
               ))}
             </ul>
         </div>

         {/* Verification Settings */}
         <div className="flex flex-col gap-4 mt-2">
           <h4 className="font-bold text-[13px] text-foreground">Verification Settings</h4>
           <div className="flex justify-between items-center text-[12px] font-medium">
             <span className="text-muted-foreground">Verification Model</span>
             <span className="text-foreground text-right">{mockVerificationData.settings.verificationModel}</span>
           </div>
           <div className="flex justify-between items-center text-[12px] font-medium">
             <span className="text-muted-foreground">Web Search</span>
             <span className="text-foreground text-right">{mockVerificationData.settings.webSearch}</span>
           </div>
           <div className="flex justify-between items-center text-[12px] font-medium">
             <span className="text-muted-foreground">Fact-Checking Level</span>
             <span className="text-foreground text-right">{mockVerificationData.settings.factCheckingLevel}</span>
           </div>
           <Button variant="link" className="px-0 mt-1 text-indigo-600 h-auto text-[13px] font-bold w-fit hover:no-underline hover:text-indigo-700 flex items-center gap-1">
             Advanced Settings <ArrowRight className="w-3.5 h-3.5" />
           </Button>
         </div>

         {/* Quick Tools */}
         <div className="flex flex-col gap-4 mt-4 mb-10">
           <h4 className="font-bold text-[13px] text-foreground">Quick Tools</h4>
           
           <div className="flex flex-col gap-3">
             <div className="flex items-center gap-3 text-[13px] font-bold text-foreground cursor-pointer hover:text-indigo-600 transition-colors group">
               <div className="w-6 h-6 rounded-md bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 flex items-center justify-center group-hover:bg-indigo-100 transition-colors">
                 <Search className="w-3.5 h-3.5" />
               </div>
               Search for Supporting Evidence
             </div>
             
             <div className="flex items-center gap-3 text-[13px] font-bold text-foreground cursor-pointer hover:text-indigo-600 transition-colors group">
               <div className="w-6 h-6 rounded-md bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 flex items-center justify-center group-hover:bg-indigo-100 transition-colors">
                 <ShieldCheck className="w-3.5 h-3.5" />
               </div>
               Check Related Research
             </div>

             <div className="flex items-center gap-3 text-[13px] font-bold text-foreground cursor-pointer hover:text-indigo-600 transition-colors group">
               <div className="w-6 h-6 rounded-md bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 flex items-center justify-center group-hover:bg-indigo-100 transition-colors">
                 <FileText className="w-3.5 h-3.5" />
               </div>
               Generate Summary Report
             </div>

             <div className="flex items-center gap-3 text-[13px] font-bold text-foreground cursor-pointer hover:text-indigo-600 transition-colors group">
               <div className="w-6 h-6 rounded-md bg-indigo-50 dark:bg-indigo-900/20 text-indigo-600 flex items-center justify-center group-hover:bg-indigo-100 transition-colors">
                 <Upload className="w-3.5 h-3.5" />
               </div>
               Export Verification Report
             </div>
           </div>
         </div>

      </div>
    </div>
  );
}
