import { Sparkles, Edit3, FileText, ShieldCheck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import type { VerificationData } from '@/services/verifyService';

interface VerifyOriginalAnswerProps {
  originalAnswer: VerificationData['originalAnswer'];
  sources?: VerificationData['sources'];
  claims?: VerificationData['claims'];
  selectedClaimIndex?: number | null;
  onClaimSelect?: (index: number | null) => void;
}

export function VerifyOriginalAnswer({ 
  originalAnswer, 
  sources,
  claims = [],
  selectedClaimIndex = null,
  onClaimSelect
}: VerifyOriginalAnswerProps) {
  
  // Helper to get color classes based on claim status
  const getHighlightColor = (status: string, isSelected: boolean) => {
    switch (status) {
      case 'Correct':
        return isSelected 
          ? 'bg-emerald-200 dark:bg-emerald-900/60 border-b-2 border-emerald-500' 
          : 'hover:bg-emerald-100 dark:hover:bg-emerald-900/40 border-b-2 border-emerald-400/50 cursor-pointer';
      case 'Incorrect':
        return isSelected 
          ? 'bg-red-200 dark:bg-red-900/60 border-b-2 border-red-500' 
          : 'hover:bg-red-100 dark:hover:bg-red-900/40 border-b-2 border-red-400/50 cursor-pointer';
      case 'Partially Correct':
        return isSelected 
          ? 'bg-amber-200 dark:bg-amber-900/60 border-b-2 border-amber-500' 
          : 'hover:bg-amber-100 dark:hover:bg-amber-900/40 border-b-2 border-amber-400/50 cursor-pointer';
      default:
        return 'cursor-pointer hover:bg-muted';
    }
  };

  // Helper to highlight text based on claims
  const renderHighlightedText = () => {
    if (!claims || claims.length === 0) return originalAnswer.text;
    
    let text = originalAnswer.text;
    const parts: React.ReactNode[] = [];
    let currentIndex = 0;

    // Find all occurrences of all claims in the text
    const matches: { start: number; end: number; claimIndex: number }[] = [];
    claims.forEach((claim, index) => {
      let startIndex = text.toLowerCase().indexOf(claim.text.toLowerCase());
      while (startIndex !== -1) {
        matches.push({
          start: startIndex,
          end: startIndex + claim.text.length,
          claimIndex: index
        });
        startIndex = text.toLowerCase().indexOf(claim.text.toLowerCase(), startIndex + 1);
      }
    });

    // Sort matches by start position
    matches.sort((a, b) => a.start - b.start);

    // Filter overlapping matches (keep the first one)
    const filteredMatches = [];
    let lastEnd = 0;
    for (const match of matches) {
      if (match.start >= lastEnd) {
        filteredMatches.push(match);
        lastEnd = match.end;
      }
    }

    if (filteredMatches.length === 0) return originalAnswer.text;

    filteredMatches.forEach((match) => {
      // Add text before match
      if (match.start > currentIndex) {
        parts.push(<span key={`text-${currentIndex}`}>{text.substring(currentIndex, match.start)}</span>);
      }
      
      // Add match span
      const claim = claims[match.claimIndex];
      const isSelected = selectedClaimIndex === match.claimIndex;
      const highlightClasses = getHighlightColor(claim.status, isSelected);
      
      parts.push(
        <span 
          key={`match-${match.start}`}
          className={`transition-colors rounded-sm px-0.5 ${highlightClasses}`}
          onClick={() => onClaimSelect?.(isSelected ? null : match.claimIndex)}
          title={claim.status}
        >
          {text.substring(match.start, match.end)}
        </span>
      );
      
      currentIndex = match.end;
    });

    // Add remaining text
    if (currentIndex < text.length) {
      parts.push(<span key={`text-${currentIndex}`}>{text.substring(currentIndex)}</span>);
    }

    return parts;
  };
  return (
    <div className="bg-card text-card-foreground shadow-sm border border-border/50 rounded-2xl shrink-0 flex flex-col p-4 md:p-8">
      <div className="flex flex-col md:flex-row md:items-center justify-between mb-4 md:mb-6 gap-3">
        <div className="flex flex-col gap-1">
          <h3 className="text-[15px] font-bold text-foreground">Original Answer</h3>
          <span className="text-[12px] text-muted-foreground md:hidden">Generated by AI</span>
        </div>
        <div className="flex items-center gap-3">
          <Badge variant="outline" className="hidden md:flex px-3 py-1.5 text-[13px] font-bold gap-2 shadow-xs bg-indigo-50/50 dark:bg-indigo-900/10 border-indigo-100 dark:border-indigo-800/30 text-indigo-700 dark:text-indigo-400 rounded-lg">
            <Sparkles className="w-3.5 h-3.5" /> {originalAnswer.model}
          </Badge>
          <Button variant="outline" size="sm" className="hidden md:flex h-9 px-4 gap-2 rounded-lg font-semibold text-[13px] border-border/60 hover:bg-muted/50 shadow-xs text-foreground">
            <Edit3 className="w-3.5 h-3.5" /> Edit Answer
          </Button>
        </div>
      </div>
      
      <p className="text-[15px] leading-relaxed text-foreground/90 font-medium mb-8">
        {renderHighlightedText()}
      </p>

      {sources && sources.length > 0 && (
        <div className="flex items-center gap-5 pt-5 border-t border-border/50">
          <span className="text-[13px] font-bold text-foreground">Sources ({sources.length})</span>
          <div className="flex items-center gap-2">
            {sources.map((source, i) => (
              <a 
                key={i}
                href={source.url}
                target="_blank"
                rel="noreferrer"
                title={source.title}
                className="w-7 h-7 rounded-lg border border-border/50 bg-background hover:bg-muted transition-colors flex items-center justify-center shadow-xs overflow-hidden"
              >
                {source.icon === 'ShieldCheck' && <ShieldCheck className="w-4 h-4 text-blue-600 dark:text-blue-400" />}
                {source.icon === 'FileText' && <FileText className="w-3.5 h-3.5 text-muted-foreground" />}
                {source.icon === 'W' && <span className="text-[11px] font-bold">W</span>}
                {!['ShieldCheck', 'FileText', 'W'].includes(source.icon) && (
                  <span className="text-[11px] font-bold text-muted-foreground">{source.domain.substring(0, 2).toUpperCase()}</span>
                )}
              </a>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
